### ISSUE TITLE
Stopped working with geckordriver

### ISSUE THREAD

**Issue by Macmasteri** [UltimaHoarder/UltimaScraper#1224]
Just run some scrapes and suddenly it stopped. Tried it with the latest commit with no luck using geckodriver. It wants me to fill in the user:pass again on site. it says "please refresh the page"

I tried the standard method auth id and session with no luck. Do I need to fill in the x-bc as well?

**Comment by kr33g33** [comment]
Same issue here as well. It stopped working at some point a few hours ago.

**Comment by mw55309** [comment]
Yep same issue, stoppd working a few hours ago

I know it's awful to have so many issues filed, but at least some pointer towards "we know about it, we're doing something" or "it's fixed" would be good - hard to know where to look
