### ISSUE TITLE
..

### ISSUE THREAD

**Issue by TisIDom** [UltimaHoarder/UltimaScraper#1641]

**Comment by LunarPenguin** [comment]
Could you elaborate on what you found?

**Comment by TisIDom** [comment]
I had to change the version of tqdm to 4.52.0.

**Comment by sturmgewehrz** [comment]
> 
> 
> Found whats wrong

i was about to scream when i read this. but to further elaborate, make sure you install everything in requirements.txt so as to ensure the correct version of tqdm is installed (which was 4.62.0 for me, not 4.52.0).
