### ISSUE TITLE
[Tutorial] Installation in macOS

### ISSUE THREAD

**Issue by Gixxa42** [UltimaHoarder/UltimaScraper#2011]
So I had a few problems installing on macOS 12.7 because of `psycopg2` so I've decided to do a little tutorial:

This is how you install the UltimaScraper on macOS:

### **Prep**

1. Install Python 3.10 from here: https://www.python.org/downloads/release/python-31011/ (Be advised, this is an old version as newer 3.10 releases do not have installers for macOS)
2. Download Postgres from here: https://postgresapp.com/downloads.html and place it into `/Applications`
3. Download UltimaScraper and unzip it to `~/Documents/UltimaScraper-main`
4. Open up a terminal window and do the following:
5. `cd ~` followed by `vi .zshrc` hit "i" and add this line into the file `export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"` to save type `:wq`
6. Use the command `source .zshrc` to reload your Terminal config.
7. Install Poetry `pipx install poetry`

### **Installation:**

1. Go into the UltimaScraper Path `cd ~/Documents/UltimaScraper-main`
2. Use poetry to install everything `poetry install`
3. Follow the tutorial from @DIGITALCRIMINAL here https://github.com/DIGITALCRIMINAL/UltimaScraper#mandatory-tutorial
4. Be advised the default auth.json will be not enabled and you need to enable it. To do this look at the last line where it says `"active": null` this should be `"active": true`
5. Start UltimaScraper with `poetry run python start_us.py`

### **Config:**

Customize you config with these settings:

https://github.com/DIGITALCRIMINAL/UltimaScraper#optional

With that everything worked for me depending on your installations with pip you might not run into the same problem as me with a fresh macOS 12.7 install.

**Comment by igobytwo** [comment]
Thanks for the tutorial @Gixxa42 - I managed to get everything installed but it looks like I'm running on a diff version of Python, does that matter?  The scraper will not respond after site selection... it just hangs at this.  Have any idea how to resolve?
![Screenshot 2023-10-25 at 8 38 22 AM](https://github.com/DIGITALCRIMINAL/UltimaScraper/assets/142369095/26d0cb02-b243-4d13-b516-b837477217f1)

**Comment by Gixxa42** [comment]
@igobytwo 

Yes, it matters, as is stated on the front page you need Python 3.10.1+. Looks like you are using 3.12 or 3.11 both will not work.

**Comment by igobytwo** [comment]
> @igobytwo
> 
> Yes, it matters, as is stated on the front page you need Python 3.10.1+. Looks like you are using 3.12 or 3.11 both will not work.

@Gixxa42 ah - seems that i get the same hang up.  I've uninstalled other versions of the Python and still just sits after I chose the site...
![Screenshot 2023-10-25 at 8 38 22 AM](https://github.com/DIGITALCRIMINAL/UltimaScraper/assets/142369095/5ffc96a2-4a34-4a56-9e17-f66ed468da1a)

**Comment by Gixxa42** [comment]
@igobytwo 

It still says that you are using python3.11 (3.11.4).

**Comment by igobytwo** [comment]
> @igobytwo
> 
> It still says that you are using python3.11 (3.11.4).

@Gixxa42 oops sorry wrong screengrab.  It's 3.10.11
![Screenshot 2023-10-25 at 1 37 57 PM](https://github.com/DIGITALCRIMINAL/UltimaScraper/assets/142369095/cbb050af-1cf0-4e76-8ed3-28ca2606b5ab)

**Comment by Gixxa42** [comment]
@igobytwo 

Hmm not sure what is causing that. Did you rerun `pipx install poetry` and `poetry install` with python 3.10.11?

**Comment by igobytwo** [comment]
> @igobytwo
> 
> Hmm not sure what is causing that. Did you rerun `pipx install poetry` and `poetry install` with python 3.10.11?

@Gixxa42 I did.  still hangs up in the same spot.  I recently migrated to a new computer and it was working fine on my last... not sure what changed.  sucks because i don't even get an error message it just hangs after i select a site.  anyway, i appreciate the help.

**Comment by yamaxiaofu** [comment]
<img width="335" alt="截屏2023-11-03 17 06 43" src="https://github.com/DIGITALCRIMINAL/UltimaScraper/assets/60559933/b45831f2-15aa-45df-968d-ee527de60de2">
why?   zsh: command not found: pipx

**Comment by Gixxa42** [comment]
@yamaxiaofu 

You need to install pipx first --> `pip3.10 install pipx`

**Comment by yamaxiaofu** [comment]
> 1. cd ~Documents/UltimaScraper-main

<img width="538" alt="截屏2023-11-04 10 03 52" src="https://github.com/DIGITALCRIMINAL/UltimaScraper/assets/60559933/ca458d4c-5b4d-4d77-a91c-e372868ddbb5">
i have no ideal that zsh: no such user or named directory: Documents

**Comment by Gixxa42** [comment]
@yamaxiaofu 

my mistake, should've been `cd ~/Documents/UltimaScraper-main`

**Comment by yamaxiaofu** [comment]
<img width="605" alt="截屏2023-11-05 10 18 38" src="https://github.com/DIGITALCRIMINAL/UltimaScraper/assets/60559933/dfe9bdbd-694b-4ed9-b4c4-9c775b36ba51">

I've had a million and one issues with Poetry recently.

**Comment by RK625** [comment]
<img width="688" alt="Screenshot 2023-11-17 at 3 51 02 am" src="https://github.com/DIGITALCRIMINAL/UltimaScraper/assets/73592219/a96e9297-0ad9-4fc8-a5c7-4427f7a768fb">

I'm also having the same issue where it just hangs...

**Comment by Gixxa42** [comment]
@RK625 This looks more like a bug with your environment and is beyond the scope of this tutorial. At the moment I'm using Python 3.10.13 via homebrew and it still works for me.

The only problem I'm currently having is I get `return self.directory_manager_users[user_id] KeyError: 369464344` in every scrape. I would say this is because of DRM and PPVs that I bought.

**Comment by Gixxa42** [comment]
@RK625 This looks more like a bug with your environment and is beyond the scope of this tutorial. At the moment I'm using Python 3.10.13 via homebrew and it still works for me.

The only problem I'm currently having is I get `return self.directory_manager_users[user_id]` in every scrape. I would say this is because of DRM and PPVs that I bought.

**Comment by msrken** [comment]
<img width="550" alt="Ảnh màn hình 2024-02-29 lúc 23 46 46" src="https://github.com/UltimaHoarder/UltimaScraper/assets/35669099/9cec89f5-fef4-4641-a082-55aff9580339">

Can you please help me? I tried to understand what you are writing but it was really hard for me. Can you make a screen recording how to install please ? Really need a video step by step.

**Comment by Gixxa42** [comment]
Hi @msrken 

I no longer use this scraper but of-scraper (https://github.com/datawhores/OF-Scraper) I suggest you do the same as the install is easier and it has a better documentation.
