### ISSUE TITLE
Are there any tutorials for windows as well?

### ISSUE THREAD

**Issue by Connimii** [UltimaHoarder/UltimaScraper#2029]
I have red through the step by step guide submitted about two weeks ago (" [Tutorial] Installation in macOS #2011 ") and failed at step 5. My Windows System says it doesnt know the commands and I dont understand cmd or the whole process of how to setup the downloader enough to troubleshoot myself. Is there any help via a windows tutorial, YouTube Video, Discord Server or even 1o1 Discord call? Thank you kindly

**Comment by Orligon** [comment]
I am in the same position, struggling with installing on windows..
