### ISSUE TITLE
Chances of New Update breaking config.

### ISSUE THREAD

**Issue by A-Random-Mf** [UltimaHoarder/UltimaScraper#2038]
I haven’t updated my instance in about a year. How high are the chances of my setup being altered significantly (metadata schema, paths)? Will the script automatically adjust all dbs without issue regardless of subscription status?

**Comment by UltimaHoarder** [comment]
UltimaScraper v7.9.0 should be the last backwards compatible version 
https://github.com/DIGITALCRIMINALS/UltimaScraper/releases/tag/v7.9.0

V8 will break everything, but a config backup will be made

**Comment by A-Random-Mf** [comment]
> UltimaScraper v7.9.0 should be the last backwards compatible version https://github.com/DIGITALCRIMINALS/UltimaScraper/releases/tag/v7.9.0
> 
> V8 will break everything, but a config backup will be made

Thanks for the info and reviving the project
