### ISSUE TITLE
Can't Download Anything

### ISSUE THREAD

**Issue by ThePornHelper** [UltimaHoarder/UltimaScraper#2040]
This is a tricky one, I've gotten it to work before it was updated. I got the auth.json file and filled it in but when I go to run the code it asks me which profile I want but I have no other options except all. No other usernames pop up, and it only takes like 0.3 sec. I don't know what is wrong at this point. Ive tried running it through a venv but I get the same results. Anyone know what is going on?

**Comment by ThePornHelper** [comment]
Update (11/17/2023):
I edited line 12 in the auth.json file from "null" to "true" and it seems to be doing something because it's freezes when I select the OnlyFans option.

**Comment by ThePornHelper** [comment]
Update (11/17/2023):
I got it working.

**Comment by draxvint** [comment]
How?

**Comment by UpstandingCitizen1** [comment]
I think I'm experiencing the same issue, the script hangs at the same point for me. Would love to know how you fixed it!
