### ISSUE TITLE
AttributeError: 'AuthModel' object has no attribute 'auth_details'. Did you mean: 'get_auth_details'?

### ISSUE THREAD

**Issue by dairyroach** [UltimaHoarder/UltimaScraper#2057]
Started getting this error yesterday.  Tried the fix that closed #2054 and even the solutions from other threads mentioned, and still get the error.

> PS C:\Users\me\Downloads\UltimaScraper-main\UltimaScraper-main> poetry run python start_us.py
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly
1
Choose Profiles: 0 = All | 1 = default
1
Traceback (most recent call last):
  File "C:\Users\me\Downloads\UltimaScraper-main\UltimaScraper-main\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\me\Downloads\UltimaScraper-main\UltimaScraper-main\start_us.py", line 44, in main
    _api = await USR.start(
  File "C:\Users\me\Downloads\UltimaScraper-main\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "C:\Users\me\Downloads\UltimaScraper-main\UltimaScraper-main\ultima_scraper\ultima_scraper.py", line 88, in start_datascraper
    setup, _subscriptions = await datascraper.account_setup(
  File "C:\Users\me\Downloads\UltimaScraper-main\UltimaScraper-main\.venv\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 415, in account_setup
    auth.auth_details.email
AttributeError: 'AuthModel' object has no attribute 'auth_details'. Did you mean: 'get_auth_details'?

**Comment by FacultativeObligatoryBotContract** [comment]
i have the same issue

**Comment by yowzersaaa** [comment]
Going into settings > config.json and changing the dynamic rules link as per [this post](https://github.com/UltimaHoarder/UltimaScraper/issues/2054#issuecomment-1870109267) worked for me, at least to get it started again.

**Comment by dairyroach** [comment]
> Going into settings > config.json and changing the dynamic rules link as per [this post](https://github.com/UltimaHoarder/UltimaScraper/issues/2054#issuecomment-1870109267) worked for me, at least to get it started again.

That was the first thing I tried, and it didn't fix the issue.

I also tried messing with the code in module_streamliner.py as described here: https://github.com/DIGITALCRIMINAL/ArchivedUltimaScraper/issues/1008#issuecomment-1637371659

And clearing the cache as outlined here:
https://github.com/DIGITALCRIMINAL/ArchivedUltimaScraper/issues/1008#issuecomment-1594095798

**Comment by ExtraIntrov** [comment]
> Going into settings > config.json and changing the dynamic rules link as per [this post](https://github.com/UltimaHoarder/UltimaScraper/issues/2054#issuecomment-1870109267) worked for me, at least to get it started again.

Also did not work for me

**Comment by djmarioka** [comment]
Me too, I changed the dynamic rules and it didn't work.

Anybody could to know how to fix this issue?. 

Thanks.

**Comment by Reveren** [comment]
The dynamic rules worked for me. Make sure you do the second step in his edited post:

> Don't forget to set your auth.json "active" back to "true" too.

**Comment by coop33r5** [comment]
@Reveren, can you post a copy of your config, i did this and i am getting the same error.

**Comment by dairyroach** [comment]
SOLVED (for me):

I was able to fix my error by getting a new cookie from my browser and pasting it into my auth.json file.  So, in my case, I suspect this version of the scraper is giving the AuthModel error instead of saying that login failed.

Closing this particular thread.
