### ISSUE TITLE
Download promblem from OF

### ISSUE THREAD

**Issue by kotsip** [UltimaHoarder/UltimaScraper#2058]
Sorry. I posted to closed issue. The script doesn't download anything from OF, About 12.20,

I updated, checked everíthing, and received this when try OF: 

/OnlyFansScrape# poetry run python3 start_us.py
[2023-12-28 22:27:18] Assigning Jobs
[2023-12-28 22:27:18] Archive Completed in 0.0 Minutes
[2023-12-28 22:27:18] Now exiting

(Fansly works.)

**Comment by InPlotITrust** [comment]
Noticing the same here. Pictures still download for me, but videos no longer download at all.

**Comment by DuckThis** [comment]
It's downloading nothing at all for me,not even images.

**Comment by RandomGuy5598** [comment]
This was happening to me back in mid November. I tried everything. I was using Firefox cookies at the time. I tried swapping to Chrome cookies and it worked with zero issue. Idk if that's the case here, but I figured it's worth mentioning.

**Comment by jeremfg** [comment]
Same. I receive an empty list of subscriptions, so the script finds nothing to download.

**Comment by fg4jerem** [comment]
Same. I receive an empty list of subscriptions. So the script finds nothing to download.

**Comment by InPlotITrust** [comment]
> This was happening to me back in mid November. I tried everything. I was using Firefox cookies at the time. I tried swapping to Chrome cookies and it worked with zero issue. Idk if that's the case here, but I figured it's worth mentioning.

I tried this and the result is the same for me. It still doesn't download the latest videos.

I noticed some bizar behaviour though. I cleared out the entire metadata and redownload everything and it works fine for old posts, but newer videos from after 25 November 2023 don't get downloaded. There's a video post from 27 November that it doesn't download and any videos from December also don't get downloaded. Images are fine.

**Comment by kotsip** [comment]
Meantime I tried the cookie change (from chrome) clear the downlaod folder nothing happen.

**Comment by DuckThis** [comment]
> This was happening to me back in mid November. I tried everything. I was using Firefox cookies at the time. I tried swapping to Chrome cookies and it worked with zero issue. Idk if that's the case here, but I figured it's worth mentioning.

How would I switch the cookies?

**Comment by kotsip** [comment]
> > This was happening to me back in mid November. I tried everything. I was using Firefox cookies at the time. I tried swapping to Chrome cookies and it worked with zero issue. Idk if that's the case here, but I figured it's worth mentioning.
> 
> How would I switch the cookies?

You have to generate a new cookie in chrome, or firefox, then insert into auth.json. 
(I tried, not helped.)

**Comment by kotsip** [comment]
I have a partial solution, I checked several issue here, perfectly works.

1. you have to change this line in config.json
"dynamic_rules_link": "https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json",
TO
"dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",

2. Chabge this sectrion in config.json from:
        "jobs": {
          "scrape": {
            "subscriptions": true,
            **"messages": true,**
            "paid_contents": true
          },
TO
        "jobs": {
          "scrape": {
            "subscriptions": true,
            **"messages": false,**
            "paid_contents": true
          },


3, You have to edit your auth.json and enable it again. Change this line from:
"active": false
TO
"active": true

**Comment by InPlotITrust** [comment]
> I have a partial solution, I checked several issue here, perfectly works.
> 
>     1. you have to change this line in config.json
>        "dynamic_rules_link": "https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json",
>        TO
>        "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
> 
>     2. Chabge this sectrion in config.json from:
>        "jobs": {
>        "scrape": {
>        "subscriptions": true,
>        **"messages": true,**
>        "paid_contents": true
>        },
>        TO
>        "jobs": {
>        "scrape": {
>        "subscriptions": true,
>        **"messages": false,**
>        "paid_contents": true
>        },
> 
> 
> 3, You have to edit your auth.json and enable it again. Change this line from: "active": false TO "active": true

Doesn't solve it for me. All those settings were already like that for me.

In another issue [2049](https://github.com/UltimaHoarder/UltimaScraper/issues/2049)  somebody brings up a copyright encryption that might be the cause of the issue. This would possible explain why older videos work for me and newer ones don't. The new ones are uploaded with a new encryption.

**Comment by kotsip** [comment]
> > I have a partial solution, I checked several issue here, perfectly works.
> > ```
> > 1. you have to change this line in config.json
> >    "dynamic_rules_link": "https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json",
> >    TO
> >    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
> > 
> > 2. Chabge this sectrion in config.json from:
> >    "jobs": {
> >    "scrape": {
> >    "subscriptions": true,
> >    **"messages": true,**
> >    "paid_contents": true
> >    },
> >    TO
> >    "jobs": {
> >    "scrape": {
> >    "subscriptions": true,
> >    **"messages": false,**
> >    "paid_contents": true
> >    },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 3, You have to edit your auth.json and enable it again. Change this line from: "active": false TO "active": true
> 
> Doesn't solve it for me. All those settings were already like that for me.
> 
> In another issue [2049](https://github.com/UltimaHoarder/UltimaScraper/issues/2049) somebody brings up a copyright encryption that might be the cause of the issue. This would possible explain why older videos work for me and newer ones don't. The new ones are uploaded with a new encryption.

I don't know - with that written solution i can download everything. It downloaded videos with dated yesterday and before yesterday.

**Comment by jeremfg** [comment]
It solved it for me too.

I'm just not sure about disabling messages though. I might try to re enable that part later.
I was surprised to find my profile inactive, that sure wouldn't help.
But I'm certain that using the proper dynamic rules URL, last updated 5 days ago, was an important part in this solution.

**Comment by fg4jerem** [comment]
It solved it for me too.

I'm just not sure about disabling messages though. I might try to re enable that part later.
I was surprised to find my profile inactive, that sure wouldn't help.
But I'm certain that using the proper dynamic rules URL, last updated 5 days ago, was an important part in this solution.

**Comment by raggabrashtrout** [comment]
This worked for me

1. you have to change this line in config.json
   "dynamic_rules_link": "https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json",
   TO
   "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",

Remove the ** from
**"messages": false,**
to "messages": false,

**Comment by djmarioka** [comment]
> This worked for me
> 
> 1. you have to change this line in config.json
>    "dynamic_rules_link": "https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json",
>    TO
>    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
> 
> Remove the ** from **"messages": false,** to "messages": false,

I've tried this  for several times, and it doesn't work. 

Could anybody help?

Thanks.

**Comment by kotsip** [comment]
> This worked for me
> 
> 1. you have to change this line in config.json
>    "dynamic_rules_link": "https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json",
>    TO
>    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
> 
> Remove the ** from **"messages": false,** to "messages": false,

the ** character is the BOLD in github. Of course that not contain the files. :)

**Comment by kotsip** [comment]
> > This worked for me
> > 
> > 1. you have to change this line in config.json
> >    "dynamic_rules_link": "https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json",
> >    TO
> >    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
> > 
> > Remove the ** from **"messages": false,** to "messages": false,
> 
> I've tried this for several times, and it doesn't work.
> 
> Could anybody help?
> 
> Thanks.

have you enabled your profile? that important.

**Comment by djmarioka** [comment]
> > > This worked for me
> > > 
> > > 1. you have to change this line in config.json
> > >    "dynamic_rules_link": "https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json",
> > >    TO
> > >    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
> > > 
> > > Remove the ** from **"messages": false,** to "messages": false,
> > 
> > 
> > I've tried this for several times, and it doesn't work.
> > Could anybody help?
> > Thanks.
> 
> have you enabled your profile? that important.

Yes, it says in auth.json "active": true

**Comment by kotsip** [comment]
> > > > This worked for me
> > > > 
> > > > 1. you have to change this line in config.json
> > > >    "dynamic_rules_link": "https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json",
> > > >    TO
> > > >    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
> > > > 
> > > > Remove the ** from **"messages": false,** to "messages": false,
> > > 
> > > 
> > > I've tried this for several times, and it doesn't work.
> > > Could anybody help?
> > > Thanks.
> > 
> > 
> > have you enabled your profile? that important.
> 
> Yes, it says in auth.json "active": true

I don't have any idea. Sorry
