### ISSUE TITLE
Unable to Authenticate

### ISSUE THREAD

**Issue by Z-8-A** [UltimaHoarder/UltimaScraper#2108]
So I know it was said that only I can fix my auth errors but has anyone else been having trouble with authentication?

I have been using the tool for the past two months no issues whatsoever (and I had 2FA enabled). I disabled 2FA, tried to edit manually, use the cookie-helper plugin, and changed browsers to no avail.

**Comment by RandomGuy5598** [comment]
Just checking... Have you replaced the old Dynamic Rules? I had zero issues until something changed recently. This fixed it for me.

https://github.com/UltimaHoarder/UltimaScraper/issues/2103#issuecomment-2159443243

**Comment by Z-8-A** [comment]
> Just checking... Have you replaced the old Dynamic Rules? I had zero issues until something changed recently. This fixed it for me.
> 
> [#2103 (comment)](https://github.com/UltimaHoarder/UltimaScraper/issues/2103#issuecomment-2159443243)

Thanks for replying. I don't see a "dynamic rules link" in my config file! I'm stupid can you help me please?

**Comment by RandomGuy5598** [comment]
> > Just checking... Have you replaced the old Dynamic Rules? I had zero issues until something changed recently. This fixed it for me.
> > [#2103 (comment)](https://github.com/UltimaHoarder/UltimaScraper/issues/2103#issuecomment-2159443243)
> 
> Thanks for replying. I don't see a "dynamic rules link" in my config file! I'm stupid can you help me please?

It's line 47 in the config.json. `"dynamic_rules_link":`
This is for an OnlyFans fix. I guess I should've asked and mentioned that. I haven't done any Fansly stuff, so idk about any of that yet.

**Comment by Z-8-A** [comment]
I don't have that line. Here's how my config.json looks like:

```
{
    "config": {
        "main_profile": "main_profile",
        "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}",
        "discord": "",
        "file_options": {
            "save_location": "/home/tariq/Data/ofscraper",
            "dir_format": "{model_username}/{responsetype}/{mediatype}/",
            "file_format": "{filename}.{ext}",
            "textlength": 0,
            "space-replacer": " ",
            "date": "MM-DD-YYYY",
            "text_type_default": "letter"
        },
        "download_options": {
            "file_size_limit": 0,
            "file_size_min": 0,
            "filter": [
                "Images",
                "Audios",
                "Videos"
            ],
            "auto_resume": false,
            "system_free_min": 0
        },
        "binary_options": {
            "mp4decrypt": "",
            "ffmpeg": ""
        },
        "cdm_options": {
            "private-key": null,
            "client-id": null,
            "key-mode-default": "cdrm2",
            "keydb_api": ""
        },
        "performance_options": {
            "download-sems": 6,
            "maxfile-sem": 0,
            "threads": 2
        },
        "advanced_options": {
            "code-execution": false,
            "dynamic-mode-default": "deviint",
            "backend": "aio",
            "downloadbars": false,
            "cache-mode": "sqlite",
            "appendlog": true,
            "custom_values": null,
            "sanitize_text": false,
            "avatar": true,
            "temp_dir": null
        },
        "responsetype": {
            "timeline": "Posts",
            "message": "Messages",
            "archived": "Archived",
            "paid": "Messages",
            "stories": "Stories",
            "highlights": "Stories",
            "profile": "Profile",
            "pinned": "Posts"
        },
        "mp4decrypt": "/home/tariq/.config/ofscraper/bin/mp4decrypt",
        "ffmpeg": "/home/tariq/.config/ofscraper/bin/ffmpeg"
    }
}
```

But I managed to get it to work by changing the dynamic-mode from "deviint" to "dc" through: `ofscraper -dr dc` I don't know what that does but it works now. thank you anyway.
